Repository openHPI/xikolo-ios, pull requests merged in 2020-06, with the labels that each got.

#784 resume background audio when video stops playing
  iOS/ViewControllers/Courses/CourseDetailsViewController.swift
  iOS/ViewControllers/Courses/CourseListViewController.swift
  iOS/ViewControllers/Courses/VideoViewController.swift
Labels: enhancement

#790 Support Drag & Drop Course into other Apps
  iOS/Extensions/Course+DragItem.swift
Labels: P3: important, feature

#776 Add loading screen for course items
  iOS/Storyboards/Base.lproj/CourseLearningsLTI.storyboard
  iOS/Storyboards/Base.lproj/CourseLearningsPeerAssessment.storyboard
  iOS/Storyboards/Base.lproj/CourseLearningsRichtext.storyboard
  iOS/Storyboards/Base.lproj/CourseLearningsVideo.storyboard
  iOS/Storyboards/Base.lproj/LoadingScreen.storyboard
  iOS/Storyboards/de.lproj/LoadingScreen.strings
  iOS/ViewControllers/Courses/LTIExerciseHintViewController.swift
  iOS/ViewControllers/Courses/PeerAssessmentHintViewController.swift
  iOS/ViewControllers/Courses/RichTextViewController.swift
  iOS/ViewControllers/Courses/VideoViewController.swift
  iOS/ViewControllers/LoadingScreen.swift
  xikolo-ios.xcodeproj/project.pbxproj
Labels: P4: nice to have, enhancement

#794 Support Drag & Drop CourseItem into other Apps
  Common/Extensions/CourseItem+URL.swift
  iOS/Data/Model/CourseItem+DragItem.swift
  iOS/Data/Model/CourseItem+NSItemProviderWriting.swift
  iOS/ViewControllers/Courses/CourseItemListViewController.swift
  iOS/ViewControllers/Courses/CourseItemViewController.swift
  iOS/Views/CourseItemCell.swift
  xikolo-ios.xcodeproj/project.pbxproj
Labels: P4: nice to have, enhancement, ios13
